packages:
  - nodejs/*
catalog:
  vitest: ^4.1.0

catalogs:
  data:
    '@electric-sql/pglite': ^0
    '@types/pg': ^8
    drizzle-kit: beta
    drizzle-orm: beta
    pg: ^8
    zod: ^4
  fastify:
    '@fastify/compress': ^8
    '@fastify/middie': ^9
    '@fastify/static': ^8
    fastify: ^5
  eslint:
    '@eslint-react/eslint-plugin': ^2
    '@eslint/js': ^9
    '@stylistic/eslint-plugin': ^5
    eslint: ^9
    eslint-import-resolver-typescript: ^4
    eslint-plugin-better-tailwindcss: ^4
    eslint-plugin-depend: ^1
    eslint-plugin-import-x: ^4
    eslint-plugin-react-hooks: ^7
    eslint-plugin-react-refresh: ^0
    eslint-plugin-storybook: ^10
    eslint-plugin-unicorn: ^63
    globals: ^17
    typescript-eslint: ^8
  react:
    '@base-ui/react': ^1
    '@react-spring/three': ^10
    '@react-three/drei': ^10
    '@react-three/fiber': ^9
    '@tanstack/react-table': ^8
    '@types/react': ^19
    '@types/react-dom': ^19
    cmdk: ^1
    date-fns: ^4
    embla-carousel-react: ^8
    input-otp: ^1
    lucide-react: ^0
    next-themes: ^0
    react: ^19
    react-day-picker: ^9
    react-dom: ^19
    react-resizable-panels: ^4
    recharts: ^2
    shadcn: ^3
    sonner: ^2
    tw-animate-css: ^1
    vaul: ^1
  storybook:
    '@storybook/addon-a11y': ^10
    '@storybook/addon-docs': ^10
    '@storybook/addon-vitest': ^10
    '@storybook/react-vite': ^10
    storybook: ^10
  typescript:
    '@types/lodash': ^4
    '@types/node': ^25
    typescript: ^5
  vite:
    '@rolldown/plugin-babel': ^0
    '@tailwindcss/vite': ^4
    '@vitejs/plugin-react': ^6
    '@vitest/browser-playwright': ^4
    '@vitest/coverage-v8': ^4
    tsdown: ^0
    vite: ^8
    vite-plugin-pwa: ^1
    vitest: ^4

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - msw
