FROM mcr.microsoft.com/devcontainers/base:noble

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install gnupg2 -y

# Copy hadolint wrapper script
COPY files/hadolint-wrapper.sh /usr/local/bin/hadolint
RUN chmod +x /usr/local/bin/hadolint